spring.application.name=soa
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=Movies API
springdoc.swagger-ui.urls[0].url=/movies.yaml

springdoc.swagger-ui.urls[1].name=Oscar API
springdoc.swagger-ui.urls[1].url=/oscar.yaml

spring.jwt.secret-key=superSecretKeysuperSecretKeysuperSecretKeysuperSecretKeysuperSecretKey
spring.jwt.expiration=3600000

spring.data.jpa.repositories.bootstrap-mode=default
spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:soa}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Spring Framework logging
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.context=DEBUG

# Component scanning
logging.level.org.springframework.context.annotation.ClassPathBeanDefinitionScanner=DEBUG

# Web MVC
logging.level.org.springframework.web.servlet=TRACE
logging.level.org.springframework.web.servlet.mvc=DEBUG

# Your application
logging.level.org.lovesoa=TRACE

