openapi: 3.0.3
info:
  title: Oscar Service API
  description: REST API для управления коллекцией фильмов.
  version: "1.0.0"

servers:
  - url: http://localhost:8080/api/oscar
    description: Локальный сервер

paths:
  /genres/redistribute-rewards/{from-genre}/{to-genre}:
    post:
      summary: Перераспределить Оскары между жанрами
      security:
        - Bearer: [ ]
      parameters:
        - in: path
          name: from-genre
          required: true
          description: Жанр, откуда забираются награды
          schema:
            $ref: './movies.yaml#/components/schemas/MovieGenre'
        - in: path
          name: to-genre
          required: true
          description: Жанр, куда передаются награды
          schema:
            $ref: './movies.yaml#/components/schemas/MovieGenre'
      responses:
        '200':
          description: Операция завершена успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  transferredCount:
                    type: integer
              examples:
                success:
                  value:
                    transferredCount: 5
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    Bearer:
      type: apiKey
      in: header
      name: Authorization
      description: >
        Введите токен с префиксом `Bearer `, например: "Bearer abcde12345".

  responses:
    BadRequest:
      description: Неверный запрос
      content:
        application/json:
          schema:
            $ref: './movies.yaml#/components/schemas/Error'
          examples:
            error:
              $ref: './movies.yaml#/components/examples/BadRequestExample'

    Unauthorized:
      description: Требуется аутентификация
      content:
        application/json:
          schema:
            $ref: './movies.yaml#/components/schemas/Error'
          examples:
            error:
              $ref: './movies.yaml#/components/examples/UnauthorizedExample'

    Forbidden:
      description: Доступ запрещен
      content:
        application/json:
          schema:
            $ref: './movies.yaml#/components/schemas/Error'
          examples:
            error:
              $ref: './movies.yaml#/components/examples/ForbiddenExample'

    UnprocessableEntity:
      description: Нарушены бизнес-правила
      content:
        application/json:
          schema:
            $ref: './movies.yaml#/components/schemas/Error'
          examples:
            error:
              $ref: './movies.yaml#/components/examples/UnprocessableEntityExample'

    InternalError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: './movies.yaml#/components/schemas/Error'
          examples:
            error:
              $ref: './movies.yaml#/components/examples/InternalErrorExample'
  examples:
    DirectorExample:
      value:
        - id: 1
          name: John Doe
          height: 180.5
          weight: 75
          location:
            x: 10
            y: 20
            z: 30
        - id: 2
          name: Jane Doe
          height: 170
          weight: 65
          location:
            x: 5
            y: 10
            z: 15